GET http://localhost:4000/api/employee/current
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiJiNTE2MTAwNC04ZDkwLTRlMmUtYmUwOS0zYmY4YWYwY2YxOWIiLCJpZCI6IjgxNmRhNDZlLWIwZTQtNDhjNi1iMTJhLTFkNjg3N2I0YmUyZCIsInR5cGUiOiJBRE1JTiIsImlhdCI6MTY3MDI5MTE2NX0.BYmPs0nHWX7s8IUaBpoqCnswN7aP3HeA1iWwl6iCmvw
