GET http://localhost:4000/api/employees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiIxODI2Mzg4Yy1kZDBiLTRhMDAtYTRiYy1kMWRjOTBkOGFmODEiLCJpZCI6ImM2NGQ4MmE3LTBmZWEtNDQ5YS05ZTJjLTQ5MzczYTJmNjM5YyIsInR5cGUiOiJBRE1JTiIsImlhdCI6MTY3MDExMTE4OX0.bozYd-Oroy7Hi_Es9cng2k6uoJSp4K9xiDxIXWXhWLc